### PR TITLE
Fix for humhub version >= 1.14.0

### LINKED ISSUE #5: Module does not work with version 1.14.1
As of humhub version 1.14.1 auth-basic module does not work anymore.

Is it possible to have an update ?

Thx

### PR DESCRIPTION
**Pull request by sebmennetrier**
Fix #5

### CODE REVIEW

**Comment by ArchBlood** [comment]
With this make sure to increase `minVersion` or implement a checker for the old class vs new class. This will help reduce reports of versioning errors.

File: Events.php [hunk 1]
```diff
@@ -25,15 +26,31 @@ public static function onBeforeRequest($event)
         if ($username != null && $password != null && $identity == null) {
             $login = new Login;
             if ($login->load(['username' => $username, 'password' => $password], '') && $login->validate()) {
-                $user = AuthClientHelpers::getUserByAuthClient($login->authClient);
-                if ($user == null) {
-                    $user = AuthClientHelpers::createUser($login->authClient);
-                }
-                if ($user != null) {
-                    Yii::$app->user->login($user);
+                if (class_exists("AuthClientService")) {
```
Comment (sebmennetrier) [inline Events.php:29]: @ArchBlood, I added this condition, is it not sufficient ?

Comment (ArchBlood) [reply Events.php:29]: > @ArchBlood, I added this condition, is it not sufficient ?

You should add the checker for `AuthClientHelpers` instead of just an `else` this can cause an error in some cases where the class can't be found in a loop, the other option would be to remove it from the loop and call `if (class_exists("AuthClientHelpers"))` as well.
